# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd6f06a922ad5e9f38e073c7e569dd6a12aac7163eea1601e3491a33523dd4c95e5e5140235819c96f42c47686a1f8d8fe2069f763bf6ff14964101b2b5fc38a

test:
  secret_key_base: 994f4933169718f22d3a2c0287709b673c2f2fd0de7eae833e051cc4a8959db5f3fa371ff24bf0543146ba5d7b47aa839520c8d8d5744984cb6e8c3b47750012

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
